version: "2"
run:
  build-tags:
    - e2e
    - mage
    - ignored
linters:
  default: all
  disable:
    - containedctx
    - depguard
    - exhaustruct
    - godox
    - ireturn
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
    - nonamedreturns
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/openshift-knative/hack/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
    rules:
      - linters:
          - wrapcheck
        path: _test\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
