name: Mage

on:
  push:
    tags:
      - v*
    branches:
      - main
      - 'release-**'
  pull_request:
    branches: 
      - main
      - 'release-**'

env:
  FORCE_COLOR: true

jobs:

  build:
    name: Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.22'
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run mage
        run: ./mage
